### ISSUE TITLE
hard crash when `DT_STRTAB` not exists 

### ISSUE THREAD

**Issue by rmNULL** [david942j/rbelftools#46]
inadvertently came across this while looking up runpath for an ELF.
https://github.com/david942j/rbelftools/blob/2c3c6523a52a18531ce8b915e1a0d23c65fc8039/lib/elftools/dynamic.rb#L114-L115

As you are  already aware of the issue how do you suggest we fix this.
exit with helpful error message seems a small improvement,
or we warn and lookup offset of `.dynstr` section([this is what patchelf does even before hunting for DT_STRTAB tag](https://github.com/NixOS/patchelf/blob/9d3fc11bc65e9af63db4de1f0182bb7392eca539/src/patchelf.cc#L1264-L1266), RIP)

**Comment by david942j** [comment]
IIRC DT_STRTAB is mandatory for an executable ELF (i.e.linked object), so for me the proper fix would be it has to detect the kind of ELF we are working on - it's an object file before linking or a linked executable file / shared library. For an object file we should find everything in the sections (object file won't have PHDR anyway), and for a linked file the DT_STRTAB should always exists unless it doesn't have a dynamic table.

Well I'm not sure whether my claim is correct, do you have examples that an executable file without the DT_STRTAB tag?

**Comment by rmNULL** [comment]
Sorry about the delayed reply.

> Well I'm not sure whether my claim is correct, do you have examples that an executable file without the DT_STRTAB tag?

I don't recall the exact ELF,  it was probably thrown by `pef-compat.elf` which lacked DT_STRTAB initially.
closing this issue as i don't have a practical ELF that depends on this. 

Thanks.
